server:
  port: 7878

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CleanCooks
    username: postgres
    password: matei
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true