server:
  port: 7879

spring:
  datasource:
    url: jdbc:postgresql://cleancooks.postgres.database.azure.com:5432/CleanCooks
    username: boris
    password: postgres1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true